version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-expenses
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expenses
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  